#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-elektro =							\
	papers/elektro/packages.tex					\
	papers/elektro/main.tex						\
	papers/elektro/references.bib					\
	papers/elektro/01_ElektrostatischesFeld.tex 			\
	papers/elektro/02_Riemann.tex 					\
	papers/elektro/03_DerKreis.tex 					\
	papers/elektro/04_KreisTransformationen.tex 

