#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kepler =						\
	papers/kepler/fig/fig-polstellen.tex			\
	papers/kepler/packages.tex				\
	papers/kepler/main.tex					\
	papers/kepler/references.bib				\
	papers/kepler/01_Einleitung.tex				\
	papers/kepler/02_Grundlagen.tex				\
	papers/kepler/03_einfache_Herleitung.tex		\
	papers/kepler/04_komplexe_Integration.tex

