#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-aircraft =							\
	papers/aircraft/packages.tex					\
	papers/aircraft/main.tex					\
	papers/aircraft/references.bib					\
	papers/aircraft/0-motivation.tex				\
	papers/aircraft/1-grundbegriffe.tex				\
	papers/aircraft/2-system.tex					\
	papers/aircraft/3-stabilitaet.tex				\
	papers/aircraft/4-eigenwerte.tex				\
	papers/aircraft/5-interpretation.tex				\
	papers/aircraft/6-beispiel.tex					\
	papers/aircraft/7-fluegel.tex					\
	papers/aircraft/8-grenzen.tex					\
	papers/aircraft/9-fazit.tex
