#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-elliptisch =						\
	papers/elliptisch/packages.tex					\
	papers/elliptisch/main.tex					\
	papers/elliptisch/references.bib				\
	papers/elliptisch/einleitung.tex				\
	papers/elliptisch/grenze.tex					\
	papers/elliptisch/funktionen.tex				\
	papers/elliptisch/anwendungen.tex				\
	papers/elliptisch/fig/koerperturmFIG.tex			\
	papers/elliptisch/fig/gradskalaFIG.tex			\
	papers/elliptisch/fig/ellipseFIG.tex			\
	papers/elliptisch/fig/ke-plotFIG.tex			\
	papers/elliptisch/fig/sn-konstruktionFIG.tex			\
	papers/elliptisch/fig/lemniskateFIG.tex			\
	papers/elliptisch/fig/troposkeinFIG.tex			\
	papers/elliptisch/fig/pendelFIG.tex			\
	papers/elliptisch/fig/darrieusFIG.tex			\
	papers/elliptisch/images/gradskala.pdf				\
	papers/elliptisch/images/ellipse.pdf				\
	papers/elliptisch/images/koerperturm.pdf			\
	papers/elliptisch/images/ke-plot.pdf				\
	papers/elliptisch/images/sn-konstruktion.pdf			\
	papers/elliptisch/images/lemniskate.pdf			\
	papers/elliptisch/images/pendel.pdf			\
	papers/elliptisch/images/troposkein.pdf			\
	papers/elliptisch/images/darrieus-rotor.jpg

