#
# Makefile
#
# (c) 2026 Damien Flury, OST Ostschweizer Fachhochschule
#
all:	kehrwert.pdf kehrwert-symmetrisch.pdf nichtungerade.pdf pol-innen.pdf \
	halbkreiskontur.pdf halbkreis-ohne-pol.pdf \
	jordan-ungleichung.pdf

kehrwert.pdf:	kehrwert.tex
	pdflatex kehrwert.tex

kehrwert-symmetrisch.pdf:	kehrwert-symmetrisch.tex
	pdflatex kehrwert-symmetrisch.tex

nichtungerade.pdf:	nichtungerade.tex
	pdflatex nichtungerade.tex

pol-innen.pdf:	pol-innen.tex
	pdflatex pol-innen.tex

halbkreiskontur.pdf:	halbkreiskontur.tex
	pdflatex halbkreiskontur.tex

halbkreis-ohne-pol.pdf:	halbkreis-ohne-pol.tex
	pdflatex halbkreis-ohne-pol.tex

jordan-ungleichung.pdf:	jordan-ungleichung.tex
	pdflatex jordan-ungleichung.tex
