#
# Makefile -- 
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	pol_auswahl.pdf								\
	bromwich_contour.pdf							\
	d_kontur.pdf								\
	keyhole_kontur.pdf							\
	pol_kette.pdf								\
	integrand_vergleich.pdf							\
	betrags_landschaft.pdf							\
	konvergenz_vergleich.pdf

pol_auswahl.pdf:	pol_auswahl.tex
	pdflatex pol_auswahl.tex

bromwich_contour.pdf:	bromwich_contour.tex
	pdflatex bromwich_contour.tex

d_kontur.pdf:	d_kontur.tex
	pdflatex d_kontur.tex

keyhole_kontur.pdf:	keyhole_kontur.tex
	pdflatex keyhole_kontur.tex

pol_kette.pdf:	pol_kette.tex
	pdflatex pol_kette.tex

integrand_vergleich.pdf:	integrand_vergleich.tex
	pdflatex integrand_vergleich.tex

betrags_landschaft.pdf:	betrags_landschaft.tex
	pdflatex betrags_landschaft.tex

konvergenz_vergleich.pdf:	konvergenz_vergleich.tex
	pdflatex konvergenz_vergleich.tex

