#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-resultante =						\
	papers/resultante/packages.tex				\
	papers/resultante/main.tex					\
	papers/resultante/references.bib			\
	papers/resultante/0_Einleitung.tex			\
	papers/resultante/1_Idee.tex				\
	papers/resultante/2_ggT.tex					\
	papers/resultante/3_Resultante.tex			\
	papers/resultante/4_RothsteinTrager.tex			\
	papers/resultante/5_Fortsetzung.tex			

