#
# Makefile.inc
#
# (c) 2026 Prof Dr Andreas Müller
#
PAPERTEXFILES = 							\
	papers/1-zahlenfunktionen.tex					\
	papers/2-anwendungen.tex					\
	papers/3-residuen.tex						\
	papers/4-speziell.tex						\
	papers/5-integration.tex					\
	papers/part2.tex						\
	papers/uebersicht.tex
