#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:									\
	gamma-reell.pdf							\
	hankelkontur.pdf						\
	komplexer-summand.pdf						\
	mellin-integrand.pdf						\
	nullstellen.pdf							\
	phasensprung.pdf

gamma-reell.pdf:	gamma-reell.tex
	pdflatex gamma-reell.tex

hankelkontur.pdf:	hankelkontur.tex
	pdflatex hankelkontur.tex

komplexer-summand.pdf:	komplexer-summand.tex
	pdflatex komplexer-summand.tex

mellin-integrand.pdf:	mellin-integrand.tex
	pdflatex mellin-integrand.tex

nullstellen.pdf:	nullstellen.tex
	pdflatex nullstellen.tex

phasensprung.pdf:	phasensprung.tex
	pdflatex phasensprung.tex
