#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fresnel =							\
	papers/fresnel/packages.tex					\
	papers/fresnel/main.tex						\
	papers/fresnel/fresnel.tex					\
	papers/fresnel/beugung-herleitung.tex				\
	papers/fresnel/references.bib

