#
# Makefile
#
# (c) 2026 Prof Dr Andreas Müller
#
all:	einseitig.pdf zweiseitig.pdf drehung.pdf

einseitig.pdf:	einseitig.tex mountain.png
	pdflatex einseitig.tex

zweiseitig.pdf:	zweiseitig.tex mountain.png
	pdflatex zweiseitig.tex

drehung.pdf:	drehung.tex
	pdflatex drehung.tex


